### ISSUE TITLE
Setting up a new task: add group names check (not allowed to have space characters)

### ISSUE THREAD

**Issue by kaaage** [tira-io/tira#560] opened 2023-11-15 09:38 UTC
The group names should follow so called `kebab-case-example`.

Now, it is possible to save the task with group names not following the schema, then later few bugs appear: e.g. new user can't register with the message "Registration is currently not possible" (as if the group list is empty or all team names were already taken), or after page refresh Register button is shown again instead of Submit.

**Comment by mam10eks** [comment] 2023-11-17 08:08
The problem is resolved via automatically slugifying all team names on the server side implemented in the commit above (not yet deployed).

**Closed** 2023-11-17 08:08 UTC
Labels: enhancement
