### ISSUE TITLE
Filtering the list of tasks breaks when the page is reloaded

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#269] opened 2022-09-24 06:47 UTC
When I filter the list of tasks, then the URL of the page changes.
E.g., here I type "click" into the search list and it works, and the URL changes so that `?q=click` is appended to the URL:

![Screenshot_20220924_084346](https://user-images.githubusercontent.com/10050886/192084007-2d90fbfe-7c39-4106-a7b1-48c8ac6f1cff.png)

When I reload this page (or directly paste the URL `https://www.tira.io/?q=click` into the browser, the page is broken.
I.e., I only get a blank page with no tasks and no image at all:

![Screenshot_20220924_084243](https://user-images.githubusercontent.com/10050886/192084081-0d9661fb-5180-4b13-9f87-fc50763c3258.png)

**Comment by BastianGrahm** [comment] 2022-09-29 14:03
Duplicate of #176

**Closed by BastianGrahm** 2022-09-29 14:03 UTC
Labels: bug
