### ISSUE TITLE
Shutdown error message shows up in interface, but shutdown seems to work

### ISSUE THREAD

**Issue by theelstner** [tira-io/tira#147] opened 2021-11-15 09:27 UTC
**Current behavior**
On shutting down the VM through the interface, an error message appears, saying the shutdown failed. Seconds later, the error message disappears, and the shutdown seems to have worked anyway. (Cannot ssh into machine, and state changed to stopped in the interface)
<img width="1328" alt="shutdown-failed-error-message" src="https://user-images.githubusercontent.com/12912413/141760676-5769c8e3-2f05-42eb-a7b2-716059dcd2ed.png">

**Expected behavior**
Error message that shutdown failed should only be displayed when the final shutdown status is failed.

**Comment by MattiWe** [comment] 2021-11-17 17:24
I can't reproduce this. Maybe this is related to #150?

**Comment by theelstner** [comment] 2021-11-18 10:09
Can't reproduce this either anymore. Was probably fixed with fixing status updates?

**Comment by MattiWe** [comment] 2021-11-18 14:25
Probably. I'll close this for now.

**Closed by MattiWe** 2021-11-18 14:25 UTC
Labels: bug
