### ISSUE TITLE
Test the new Software Page behind Dirsaptor

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#264] opened 2022-09-15 07:31 UTC
This might be a good issue so that @BastianGrahm and @Dumpling97 can collaborate to ensure a smooth handover for the discourse things and related stuff.

Test all the workflows of the new software page and write down things that do not work and things that can be improved.

For instance things as (I only found them during fast clicking around, there might be other such issues):

- [At this page](https://www.tira.io/task/buw-nlp-course-summer-term-2022/user/nlptasks-baseline) I noticed that the upload submissions are empty after I have clicked on the Docker images icon.
- Running a Docker software does not work anymore (The error in the network tools is "Blocked: NS_BINDING_ABORTED". So it looks like the request is not send to the server)
- Running Jobs are not displayed.
- Write also down usability issues: Are there situations where you do not know what to do? What would help you? For instance, the upload docker images window is currently missing the "personalized documentation" that I wrote and I guess without this it is not userfriendly.

**Comment by BastianGrahm** [comment] 2022-09-15 14:12
I just clicked around a little and after heading to the "Virtual Machine Submission" none of the button clicks do anything anymore. So I can't change to the other tabs, also adding a software or starting the VM doesn't trigger any view changes. Anyway, when I reload the page the actions that I started with my clicks worked. Softwares got created and the machine is starting.

**Comment by BastianGrahm** [comment] 2022-09-16 10:01
When uploading a file in the "Upload Submission" tab and it works fine the response is 
![image](https://user-images.githubusercontent.com/29681076/190614087-44a5c9fc-785b-4448-acdd-240f584110ab.png)
Maybe a little misleading.

**Comment by BastianGrahm** [comment] 2022-09-16 11:34
> I just clicked around a little and after heading to the "Virtual Machine Submission" none of the button clicks do anything anymore. So I can't change to the other tabs, also adding a software or starting the VM doesn't trigger any view changes. Anyway, when I reload the page the actions that I started with my clicks worked. Softwares got created and the machine is starting.
> 
> EDIT: Actually the "Connection Info" button does work in this scenario.

So this is due to an error thrown here https://github.com/tira-io/tira/blob/c29be3480418fdac7cc833bb1ad12bb03f960d6d/application/src/tira/frontend/src/components/vmsubmissionpanel.vue#L350-L362
The for loop loops over the indices of the softwares but then ends on a variable called `_super`. It obviously tries to access `this.software[_super].software` but this doesn't exist so this breaks everything. 
This is probably connected to this: https://github.com/emberjs/ember.js/issues/19289

**Comment by BastianGrahm** [comment] 2022-09-20 16:56
Most of this was fixed by https://github.com/tira-io/tira/commit/9fa2bda5e0160ca48fd286a99e7a171726133ff9.
There still are 2 bugs we could find immediately
- When adding a new docker container the page has to be reloaded for it to be shown
- when running a docker container the "running processes panel" is not directly shown but only after reloading
  - when adding more processes to it they are covered by the poll that happens every 10s so they are then loaded dynamically

**Comment by BastianGrahm** [comment] 2022-09-21 13:38
Adding a new docker container now instantly updates the list of existing containers. Same for container deletion. For reference see 9fa2bda5e0160ca48fd286a99e7a171726133ff9.

**Comment by BastianGrahm** [comment] 2022-09-21 15:01
Adding a software now works as intended via dfc2f6b842e8178e828f8d0c2d47208f7d88b7de

**Comment by BastianGrahm** [comment] 2022-09-27 16:25
Everything here should be solved with the newest version. Closing this for now.

**Closed by BastianGrahm** 2022-09-27 16:25 UTC
Labels: enhancement
